package: blogger
version: '0.0.0'

page:
  title: 'translate:title'
  subpages:
    entries: { title: 'translate:page_entries' }
    categories: { title: 'translate:page_categories'}
    tags: { title: 'translate:page_tags'}

requires:
  packages:
    redactor2: '^3.0.1'
